### ISSUE TITLE
Error when creating ml4t environment using the yml file

### ISSUE THREAD

**Issue by ssilverac** [PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading#3]
Hello
I have tried to create an environment using the environment.yml file provided but I get the following error:

Solving environment: failed

ResolvePackageNotFound:
  - gcc_linux-64=7.2.0
  - binutils_impl_linux-64=2.28.1
  - gxx_linux-64=7.2.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gmp=6.1.2
  - pango=1.42.4
  - dbus=1.13.2
  - gcc_impl_linux-64=7.2.0
  - binutils_linux-64=7.2.0
  - gxx_impl_linux-64=7.2.0
  - ncurses=6.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - readline=7.0
  - expat=2.2.6
  - fribidi=1.0.5
  - libgfortran-ng=7.3.0
  - graphviz=2.40.1
  - libedit=3.1.20170329

is there any way I can fix this? thanks for the help

**Comment by jgardezi** [comment]
I am having the same issue, @ssilverac did you resolved this issue? I am having this issue on windows 10.

**Comment by ssilverac** [comment]
Hi @jgardezi 
I have resolved this issue
https://github.com/stefan-jansen/machine-learning-for-trading

visit this repo and there should be a environment_windows_yml file in there that you can use. basically what I did was I deleted all the packages that could not be resolved from the original yml file and then it worked after that. the issue is that these environments listed here are for Linux, not windows, so some packages did not work.
also, this repo here by packt publishing is not regularly maintained, so if you have any further issues, use the GitHub linked above instead as you will likely not get an answer here

**Comment by jgardezi** [comment]
Thank you @ssilverac, I will have a look and probably use your repository for future references.

**Comment by gaurav-packt** [comment]
Thank you for the resolution which will help the readers.
