### ISSUE TITLE
Quandl Wiki prices are deprecated 

### ISSUE THREAD

**Issue by spawnaga** [PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading#6]

**Comment by spawnaga** [comment]
The Wiki Prices Metadata or wiki metadata under Companies from quandl has been deprecated. Any suggestions or alternatives for data use? I do not know what this csv file contains exactly so that I can replace it from another resource. If you can show me a print screen image or tell me what the columns are so that I can search for another resource.

**Comment by flykule** [comment]
Have you found alternative source?

**Comment by spawnaga** [comment]
> Have you found alternative source?

Not exactly, they have one that it requires payment in quandl but it was not exactly as the other one and I ended getting error messages in my  code which it frustrated me and made me quit.

**Comment by Alibek80** [comment]
I also cannot find it on Quandl.
What is included in this metadata?  Is it possible to proceed further in the book without this data?

**Comment by cheenweekiang** [comment]
Go to his second book github > https://github.com/stefan-jansen/machine-learning-for-trading for the data
