### ISSUE TITLE
data-prep.jpnb

### ISSUE THREAD

**Issue by angelowra** [PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading#8]
Hi there,
in the book, chapter 2 you mention the existence of the below jupyter notebook but I cant see it in any directory. 

thks Angelo

**Comment by ManikandanKurup-Packt** [comment]
Hello  @angelowra,
Apologies for the delayed reply.

Can you mention let us know which specific notebook are you referring to?

Thanks,
Mani
