### ISSUE TITLE
ResolvePackageNotFound: error

### ISSUE THREAD

**Issue by silent0506** [PacktPublishing/Hands-On-Machine-Learning-for-Algorithmic-Trading#9]
Hello. I recently bought a book and am reading it well. Thank you.

I'm going to practice the code.

Using 'conda env create -f environment.yml'

I was trying to install my environment, but the following error occurred:

What should I do? (I am a Windows os user.)

`ResolvePackageNotFound:
  - binutils_impl_linux-64=2.28.1
  - gxx_impl_linux-64=7.2.0
  - gxx_linux-64=7.2.0
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - readline=7.0
  - gcc_linux-64=7.2.0
  - gmp=6.1.2
  - libuuid=1.0.3
  - gstreamer=1.14.0
  - graphviz=2.40.1
  - dbus=1.13.2
  - binutils_linux-64=7.2.0
  - expat=2.2.6
  - libgfortran-ng=7.3.0
  - gcc_impl_linux-64=7.2.0
  - ncurses=6.1
  - gst-plugins-base=1.14.0
  - libedit=3.1.20170329`

**Comment by joshuacox** [comment]
Yes the environment files are out of date, and also way too big,  I was trying to update the environment files but because they are so huge it takes way too long for the solver to work out conflicts (like an over an hour for each time I try to create the environment and when it dumps out the conflicts). 

There should be environment files for each chapter. This would keep things much more manageable.

**Comment by TheStoneSpain** [comment]
@silent0506, 

You can use this link with instructions to install the environment correctly, this is the one I used in windows

https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-jul-2020.ipynb

do you have GPU ?

GoodLuck.

**Comment by TheStoneSpain** [comment]
hi there @deepesh-packt , I was able to help @joshuacox, but I was wondering if there is a forum, channel  somewhere were we can share ideas, problems, etc about the book.

Or someone can take the initiative to create a slack channel.

thanks!

**Comment by deepesh-packt** [comment]
Hi @TheStoneMX ,

If you have questions/ideas about any aspect of this book, mention the book title in the subject of your message and email us at customercare@packtpub.com.

Although we have taken every care to ensure the accuracy of our content, mistakes do happen. If you have found a mistake in this book, we would be grateful if you would report this to us. Please visit www.packtpub.com/support/errata, selecting your book, clicking on the Errata Submission Form link, and entering the details.

Thanks.
